static void beep(unsigned int freq)
static void braille_write(u16 *buf)
static void vc_follow_cursor(struct vc_data *vc)
static void vc_maybe_cursor_moved(struct vc_data *vc)
static void vc_refresh(struct vc_data *vc)
static int keyboard_notifier_call(struct notifier_block *blk,  unsigned long code, void *_param)
static int vt_notifier_call(struct notifier_block *blk,    unsigned long code, void *_param)
int braille_register_console(struct console *console, int index,char *console_options, char *braille_options)
int braille_unregister_console(struct console *console)