static int acpi_ac_get_state(struct acpi_ac *ac)
static int get_ac_property(struct power_supply *psy,   enum power_supply_property psp,   union power_supply_propval *val)
static int acpi_ac_seq_show(struct seq_file *seq, void *offset)
static int acpi_ac_add_fs(struct acpi_ac *ac)
static int acpi_ac_remove_fs(struct acpi_ac *ac)
static void acpi_ac_notify(struct acpi_device *device, u32 event)
static int acpi_ac_battery_notify(struct notifier_block *nb,  unsigned long action, void *data)
static int __init thinkpad_e530_quirk(const struct dmi_system_id *d)
static int __init ac_do_not_check_pmic_quirk(const struct dmi_system_id *d)
static int acpi_ac_add(struct acpi_device *device)
static int acpi_ac_resume(struct device *dev)
static int acpi_ac_remove(struct acpi_device *device)
static int __init acpi_ac_init(void)
static void __exit acpi_ac_exit(void)