unsigned int gxmd5_F(unsigned int x, unsigned int y, unsigned int z)
unsigned int gxmd5_G(unsigned int x, unsigned int y, unsigned int z)
unsigned int gxmd5_H(unsigned int x, unsigned int y, unsigned int z)
unsigned int gxmd5_I(unsigned int x, unsigned int y, unsigned int z)
unsigned int gxmd5_rotate_left(unsigned int x, int n)
void gxmd5_FF(unsigned int *a, unsigned int b, unsigned int c, unsigned int d, unsigned int x, unsigned int s, unsigned int ac)
void gxmd5_GG(unsigned int *a, unsigned int b, unsigned int c, unsigned int d, unsigned int x, unsigned int s, unsigned int ac) 
void gxmd5_HH(unsigned int *a, unsigned int b, unsigned int c, unsigned int d, unsigned int x, unsigned int s, unsigned int ac) 
void gxmd5_II(unsigned int *a, unsigned int b, unsigned int c, unsigned int d, unsigned int x, unsigned int s, unsigned int ac) 
void gxmd5_decode(unsigned int * output, unsigned char *input, unsigned int len)
void CGXDLMSMD5::Encode(unsigned char * output, unsigned int *input, unsigned int len)
void CGXDLMSMD5::Transform(unsigned char* block, unsigned int *state)
int CGXDLMSMD5::Update(unsigned char* data, unsigned int len, unsigned char* buffer, unsigned int* count, unsigned int* state)
int CGXDLMSMD5::Encrypt(CGXByteBuffer& data, CGXByteBuffer& digest)
